---
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_include:
          regex: '.+'
          message: 'Your title can contain anything'