version: 2
mergeable:
  - when: pull_request.*
    name: "Size check"
    validate:
      - do: size
        ignore: ["**/*.json", "**/*.md", "**/*.yml", "**/*.yaml", "**/*.properties"]
        lines:
          max:
            count: 600
            message: The change is very big for reviewing as it contains more than 600 lines.
    pass:
      - do: checks
        status: success
        payload:
          title: Pull request size is within limits.
          summary: Pull request size is within limits.
    fail:
      - do: checks
        status: failure
        payload:
          title: Pull request size is too large! Click on Details for more info ->
          summary: |
            The pull request size is too large. Aim for less than 600 lines of additions and deletions, or try to split the PR.
            This doesn't mean that your code can't be merged, but it means that it needs to be looked carefully by the repository
            owners, and merged by a repository admin.
    error:
      - do: checks
        status: action_required
        payload:
          title: Something went wrong, could not determine PR Size.
          summary: Something went wrong with Mergeable. Try re-running the validation.
  - when: pull_request.*
    name: 'Label Check'
    validate:
      - do: label
        and:
          - must_include:
             regex: 'squad: [a-z]+[a-z\-]+'
             regex_flag: 'none'
             message: 'You need to add squad label for your PR'
          - must_include:
             regex: 'tribe: [a-z]+[a-z\-]+'
             regex_flag: 'none'
             message: 'You need to add tribe label for your PR'
          - must_include:
             regex: 'type: [a-z0-9]+'
             regex_flag: 'none'
             message: 'You need to add type label for your PR'
  - when: pull_request.*
    name: "Assign reviewer"
    validate: []
    pass:
      - do: assign
        assignees: [ '@iammuho' ]
