---
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: headRef
        must_include:
          regex: '.+'
          message: 'Your branch name can contain anything'
      - do: title
        must_exclude:
          regex: ^\[WIP\]