version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: HelloTech approval
    validate:
      - do: approvals
        min:
          count: 1
          message: 'Developers from all of the required teams, regarding to CODEOWNERS file, need to approve this PR'
        limit:
          owners: true
        block:
          changes_requested: true
          message: 'To merge this PR, you must complete the Change Requests'
  - when: pull_request.opened, pull_request.reopened, pull_request.synchronize, pull_request.labeled, pull_request.unlabeled
    name: 'Check tribe/squad labels'
    filter:
      - do: repository
        topics:
          must_include:
            regex: '^disable-mergeable$'
    validate:
      - do: label
        and:
          - must_include:
              regex: 'squad: [a-z]+[a-z\-]+'
              regex_flag: 'none'
              message: 'You need to add squad label for your PR'
          - must_include:
              regex: 'tribe: [a-z]+[a-z\-]+'
              regex_flag: 'none'
              message: 'You need to add tribe label for your PR'