---
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: branch
        must_include:
           regex: '(^|[-\/])(major|release|minor|feature|patch|issue|hotfix|dependabot\/|whitesource)[-\/](\b[A-Z][A-Z0-9]+-\d+\b).+$'
           message: 'Custom message...'
      - do: description
        must_include:
          regex: \b[A-Z][A-Z0-9]+-\d+\b
          message: All pull requests must include a JIRA ticket on it.
  - when: pull_request.*
    validate:
      - do: description
        must_include:
          regex: \b[A-Z][A-Z0-9]+-\d+\b
          message: All pull requests must include a JIRA ticket on it.
    fail:
      - do: comment
        payload:
          body: >
            The pull request description must have a JIRA ticket
