---
name: example-1
on: [push]
jobs:
  run-go-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Build and push Docker base image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            geass/php:latest
            geass/php:1
